### ISSUE TITLE
Unable to Download System configuration file under Admin tab

### ISSUE THREAD

**Issue by naveen-fractlio** [fractalio/integralstor-gridcell#107] opened 2016-01-08 09:14 UTC
System configuration file is not downloading when we select Download button error saying...

"An error occurred when processing your request : global name 'display_name' is not defined

Error Details : "

Recreate steps:

Admin tab >> download system configuration >> Download.

screenshot:

![screenshot from 2016-01-08 14-38-23](https://cloud.githubusercontent.com/assets/11418556/12194462/4dee94d0-b616-11e5-8f47-990e27a14a16.png)

**Comment by fractalram** [comment] 2016-01-08 09:59
Duplicate of issue 94 - fixed but will keep #94 open so we can track on the next build.

**Closed by fractalram** 2016-01-08 09:59 UTC
Labels: bug, duplicate
